package com.voidwhile.cisn.entity;

public class Answer {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cisn_answer.id
	 * @mbg.generated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cisn_answer.orders
	 * @mbg.generated
	 */
	private Integer orders;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cisn_answer.question_id
	 * @mbg.generated
	 */
	private Integer questionId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cisn_answer.label
	 * @mbg.generated
	 */
	private String label;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cisn_answer.val
	 * @mbg.generated
	 */
	private String val;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cisn_answer.id
	 * @return  the value of cisn_answer.id
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cisn_answer.id
	 * @param id  the value for cisn_answer.id
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cisn_answer.orders
	 * @return  the value of cisn_answer.orders
	 * @mbg.generated
	 */
	public Integer getOrders() {
		return orders;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cisn_answer.orders
	 * @param orders  the value for cisn_answer.orders
	 * @mbg.generated
	 */
	public void setOrders(Integer orders) {
		this.orders = orders;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cisn_answer.question_id
	 * @return  the value of cisn_answer.question_id
	 * @mbg.generated
	 */
	public Integer getQuestionId() {
		return questionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cisn_answer.question_id
	 * @param questionId  the value for cisn_answer.question_id
	 * @mbg.generated
	 */
	public void setQuestionId(Integer questionId) {
		this.questionId = questionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cisn_answer.label
	 * @return  the value of cisn_answer.label
	 * @mbg.generated
	 */
	public String getLabel() {
		return label;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cisn_answer.label
	 * @param label  the value for cisn_answer.label
	 * @mbg.generated
	 */
	public void setLabel(String label) {
		this.label = label;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cisn_answer.val
	 * @return  the value of cisn_answer.val
	 * @mbg.generated
	 */
	public String getVal() {
		return val;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cisn_answer.val
	 * @param val  the value for cisn_answer.val
	 * @mbg.generated
	 */
	public void setVal(String val) {
		this.val = val;
	}
}