package com.voidwhile.cisn.entity;

import java.util.List;

public class Question {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cisn_question.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cisn_question.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cisn_question.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cisn_question.orders
     *
     * @mbg.generated
     */
    private Integer orders;
    
    List<Answer> answers;
    
    List<StdAnswer> stdAnswers;
    
    public List<Answer> getAnswers() {
		return answers;
	}

	public void setAnswers(List<Answer> answers) {
		this.answers = answers;
	}

	public List<StdAnswer> getStdAnswers() {
		return stdAnswers;
	}

	public void setStdAnswers(List<StdAnswer> stdAnswers) {
		this.stdAnswers = stdAnswers;
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cisn_question.paper_id
     *
     * @mbg.generated
     */
    private Integer paperId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cisn_question.id
     *
     * @return the value of cisn_question.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cisn_question.id
     *
     * @param id the value for cisn_question.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cisn_question.title
     *
     * @return the value of cisn_question.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cisn_question.title
     *
     * @param title the value for cisn_question.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cisn_question.type
     *
     * @return the value of cisn_question.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cisn_question.type
     *
     * @param type the value for cisn_question.type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cisn_question.orders
     *
     * @return the value of cisn_question.orders
     *
     * @mbg.generated
     */
    public Integer getOrders() {
        return orders;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cisn_question.orders
     *
     * @param orders the value for cisn_question.orders
     *
     * @mbg.generated
     */
    public void setOrders(Integer orders) {
        this.orders = orders;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cisn_question.paper_id
     *
     * @return the value of cisn_question.paper_id
     *
     * @mbg.generated
     */
    public Integer getPaperId() {
        return paperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cisn_question.paper_id
     *
     * @param paperId the value for cisn_question.paper_id
     *
     * @mbg.generated
     */
    public void setPaperId(Integer paperId) {
        this.paperId = paperId;
    }
}