package com.voidwhile.cisn.entity;

public class StdAnswer extends Answer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cisn_std_answer.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cisn_std_answer.question_id
     *
     * @mbg.generated
     */
    private Integer questionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cisn_std_answer.answer_id
     *
     * @mbg.generated
     */
    private Integer answerId;
    
    private String label;
    private String val;

    public String getVal() {
		return val;
	}

	public void setVal(String val) {
		this.val = val;
	}

	public String getLabel() {
		return label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cisn_std_answer.id
     *
     * @return the value of cisn_std_answer.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cisn_std_answer.id
     *
     * @param id the value for cisn_std_answer.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cisn_std_answer.question_id
     *
     * @return the value of cisn_std_answer.question_id
     *
     * @mbg.generated
     */
    public Integer getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cisn_std_answer.question_id
     *
     * @param questionId the value for cisn_std_answer.question_id
     *
     * @mbg.generated
     */
    public void setQuestionId(Integer questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cisn_std_answer.answer_id
     *
     * @return the value of cisn_std_answer.answer_id
     *
     * @mbg.generated
     */
    public Integer getAnswerId() {
        return answerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cisn_std_answer.answer_id
     *
     * @param answerId the value for cisn_std_answer.answer_id
     *
     * @mbg.generated
     */
    public void setAnswerId(Integer answerId) {
        this.answerId = answerId;
    }
}