package com.voidwhile.cisn.entity;

import java.util.Date;

public class Test {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cisn_test.id
	 * @mbg.generated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cisn_test.tester
	 * @mbg.generated
	 */
	private String tester;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cisn_test.test_time
	 * @mbg.generated
	 */
	private Date testTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cisn_test.paper_id
	 * @mbg.generated
	 */
	private Integer paperId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cisn_test.submit_time
	 * @mbg.generated
	 */
	private Date submitTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cisn_test.id
	 * @return  the value of cisn_test.id
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cisn_test.id
	 * @param id  the value for cisn_test.id
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cisn_test.tester
	 * @return  the value of cisn_test.tester
	 * @mbg.generated
	 */
	public String getTester() {
		return tester;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cisn_test.tester
	 * @param tester  the value for cisn_test.tester
	 * @mbg.generated
	 */
	public void setTester(String tester) {
		this.tester = tester;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cisn_test.test_time
	 * @return  the value of cisn_test.test_time
	 * @mbg.generated
	 */
	public Date getTestTime() {
		return testTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cisn_test.test_time
	 * @param testTime  the value for cisn_test.test_time
	 * @mbg.generated
	 */
	public void setTestTime(Date testTime) {
		this.testTime = testTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cisn_test.paper_id
	 * @return  the value of cisn_test.paper_id
	 * @mbg.generated
	 */
	public Integer getPaperId() {
		return paperId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cisn_test.paper_id
	 * @param paperId  the value for cisn_test.paper_id
	 * @mbg.generated
	 */
	public void setPaperId(Integer paperId) {
		this.paperId = paperId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cisn_test.submit_time
	 * @return  the value of cisn_test.submit_time
	 * @mbg.generated
	 */
	public Date getSubmitTime() {
		return submitTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cisn_test.submit_time
	 * @param submitTime  the value for cisn_test.submit_time
	 * @mbg.generated
	 */
	public void setSubmitTime(Date submitTime) {
		this.submitTime = submitTime;
	}
}