package com.voidwhile.cisn.mapper;

import com.voidwhile.cisn.entity.Answer;

public interface AnswerMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cisn_answer
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cisn_answer
	 * @mbg.generated
	 */
	int insert(Answer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cisn_answer
	 * @mbg.generated
	 */
	int insertSelective(Answer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cisn_answer
	 * @mbg.generated
	 */
	Answer selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cisn_answer
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Answer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cisn_answer
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Answer record);
}