package com.voidwhile.cisn.mapper;

import java.util.List;

import com.voidwhile.cisn.entity.Paper;

public interface PaperMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cisn_paper
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cisn_paper
     *
     * @mbg.generated
     */
    int insert(Paper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cisn_paper
     *
     * @mbg.generated
     */
    int insertSelective(Paper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cisn_paper
     *
     * @mbg.generated
     */
    Paper selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cisn_paper
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Paper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cisn_paper
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Paper record);

	List<Paper> selectAll();
}