package com.voidwhile.cisn.mapper;

import java.util.List;
import java.util.Map;

import com.voidwhile.cisn.entity.Question;

public interface QuestionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cisn_question
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cisn_question
     *
     * @mbg.generated
     */
    int insert(Question record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cisn_question
     *
     * @mbg.generated
     */
    int insertSelective(Question record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cisn_question
     *
     * @mbg.generated
     */
    Question selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cisn_question
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Question record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cisn_question
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Question record);

	List<Question> selectByPaper(Integer paperId);
}