package com.voidwhile.cisn.mapper;

import com.voidwhile.cisn.entity.StdAnswer;

public interface StdAnswerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cisn_std_answer
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cisn_std_answer
     *
     * @mbg.generated
     */
    int insert(StdAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cisn_std_answer
     *
     * @mbg.generated
     */
    int insertSelective(StdAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cisn_std_answer
     *
     * @mbg.generated
     */
    StdAnswer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cisn_std_answer
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(StdAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cisn_std_answer
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(StdAnswer record);
}