package com.voidwhile.cisn.mapper;

import com.voidwhile.cisn.entity.Test;

public interface TestMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cisn_test
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cisn_test
	 * @mbg.generated
	 */
	int insert(Test record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cisn_test
	 * @mbg.generated
	 */
	int insertSelective(Test record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cisn_test
	 * @mbg.generated
	 */
	Test selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cisn_test
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Test record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cisn_test
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Test record);
}