package com.voidwhile.cisn.mapper;

import com.voidwhile.cisn.entity.TestAnswer;

public interface TestAnswerMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cisn_test_answer
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cisn_test_answer
	 * @mbg.generated
	 */
	int insert(TestAnswer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cisn_test_answer
	 * @mbg.generated
	 */
	int insertSelective(TestAnswer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cisn_test_answer
	 * @mbg.generated
	 */
	TestAnswer selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cisn_test_answer
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(TestAnswer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cisn_test_answer
	 * @mbg.generated
	 */
	int updateByPrimaryKey(TestAnswer record);
}